// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/quotar.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateDirReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Size                 int64    `protobuf:"varint,2,opt,name=size" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateDirReq) Reset()         { *m = CreateDirReq{} }
func (m *CreateDirReq) String() string { return proto.CompactTextString(m) }
func (*CreateDirReq) ProtoMessage()    {}
func (*CreateDirReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_quotar_b6a38f49c0b7637f, []int{0}
}
func (m *CreateDirReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDirReq.Unmarshal(m, b)
}
func (m *CreateDirReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDirReq.Marshal(b, m, deterministic)
}
func (dst *CreateDirReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDirReq.Merge(dst, src)
}
func (m *CreateDirReq) XXX_Size() int {
	return xxx_messageInfo_CreateDirReq.Size(m)
}
func (m *CreateDirReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDirReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDirReq proto.InternalMessageInfo

func (m *CreateDirReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateDirReq) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type CreateDirResp struct {
	RetCode              int32    `protobuf:"varint,1,opt,name=ret_code,json=retCode" json:"ret_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateDirResp) Reset()         { *m = CreateDirResp{} }
func (m *CreateDirResp) String() string { return proto.CompactTextString(m) }
func (*CreateDirResp) ProtoMessage()    {}
func (*CreateDirResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_quotar_b6a38f49c0b7637f, []int{1}
}
func (m *CreateDirResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDirResp.Unmarshal(m, b)
}
func (m *CreateDirResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDirResp.Marshal(b, m, deterministic)
}
func (dst *CreateDirResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDirResp.Merge(dst, src)
}
func (m *CreateDirResp) XXX_Size() int {
	return xxx_messageInfo_CreateDirResp.Size(m)
}
func (m *CreateDirResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDirResp.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDirResp proto.InternalMessageInfo

func (m *CreateDirResp) GetRetCode() int32 {
	if m != nil {
		return m.RetCode
	}
	return 0
}

func init() {
	proto.RegisterType((*CreateDirReq)(nil), "pb.CreateDirReq")
	proto.RegisterType((*CreateDirResp)(nil), "pb.CreateDirResp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Quotar service

type QuotarClient interface {
	CreateDir(ctx context.Context, in *CreateDirReq, opts ...grpc.CallOption) (*CreateDirResp, error)
}

type quotarClient struct {
	cc *grpc.ClientConn
}

func NewQuotarClient(cc *grpc.ClientConn) QuotarClient {
	return &quotarClient{cc}
}

func (c *quotarClient) CreateDir(ctx context.Context, in *CreateDirReq, opts ...grpc.CallOption) (*CreateDirResp, error) {
	out := new(CreateDirResp)
	err := grpc.Invoke(ctx, "/pb.Quotar/CreateDir", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Quotar service

type QuotarServer interface {
	CreateDir(context.Context, *CreateDirReq) (*CreateDirResp, error)
}

func RegisterQuotarServer(s *grpc.Server, srv QuotarServer) {
	s.RegisterService(&_Quotar_serviceDesc, srv)
}

func _Quotar_CreateDir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDirReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuotarServer).CreateDir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Quotar/CreateDir",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuotarServer).CreateDir(ctx, req.(*CreateDirReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Quotar_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Quotar",
	HandlerType: (*QuotarServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDir",
			Handler:    _Quotar_CreateDir_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/quotar.proto",
}

func init() { proto.RegisterFile("pb/quotar.proto", fileDescriptor_quotar_b6a38f49c0b7637f) }

var fileDescriptor_quotar_b6a38f49c0b7637f = []byte{
	// 156 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0x48, 0xd2, 0x2f,
	0x2c, 0xcd, 0x2f, 0x49, 0x2c, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52,
	0x32, 0xe3, 0xe2, 0x71, 0x2e, 0x4a, 0x4d, 0x2c, 0x49, 0x75, 0xc9, 0x2c, 0x0a, 0x4a, 0x2d, 0x14,
	0x12, 0xe2, 0x62, 0xc9, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3,
	0x41, 0x62, 0xc5, 0x99, 0x55, 0xa9, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0xcc, 0x41, 0x60, 0xb6, 0x92,
	0x16, 0x17, 0x2f, 0x92, 0xbe, 0xe2, 0x02, 0x21, 0x49, 0x2e, 0x8e, 0xa2, 0xd4, 0x92, 0xf8, 0xe4,
	0xfc, 0x14, 0x88, 0x66, 0xd6, 0x20, 0xf6, 0xa2, 0xd4, 0x12, 0xe7, 0xfc, 0x94, 0x54, 0x23, 0x2b,
	0x2e, 0xb6, 0x40, 0xb0, 0xbd, 0x42, 0x06, 0x5c, 0x9c, 0x70, 0x5d, 0x42, 0x02, 0x7a, 0x05, 0x49,
	0x7a, 0xc8, 0x96, 0x4b, 0x09, 0xa2, 0x89, 0x14, 0x17, 0x24, 0xb1, 0x81, 0x9d, 0x6a, 0x0c, 0x08,
	0x00, 0x00, 0xff, 0xff, 0x09, 0x04, 0x7a, 0x38, 0xbd, 0x00, 0x00, 0x00,
}
